/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Admin;

/**
 *
 * @author miiny
 */

import Tracker.AttendanceTracker;
import com.opencsv.CSVReader;
import java.io.FileReader;
import java.io.IOException;
import java.time.Duration;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import model.Employee;
import model.EmployeeManager;
import java.util.List;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import model.*;



public final class AdminDashboard extends javax.swing.JFrame {

    public static EmployeeManager employeeManager = new EmployeeManager();
    private Employee selectedEmployee = null;
    private boolean isEditing = false;
    
    private String selectedEmployeeId = null;


    
   

    public AdminDashboard() {
        initComponents();
        loadTableData(employeeManager.getAllEmployees());
        setFieldsEditable(false);
        loadEmployeeDataFromCSV();
        updateEmployeeTable();
        employeeManager.loadPayrollDataFromCSV();
        employeeManager.loadAttendanceDataFromCSV();
        

        


    }
    //para hindi ma eedit mga info kapag hindi clinick yung edit
// kapag clinick duon palang pwede i-edit
    
    private void setFieldsEditable(boolean editable) {
    txtID.setEditable(editable);
    txtName.setEditable(editable);
    txtPosition.setEditable(editable);
    txtStatus.setEditable(editable);
    txtBirthday.setEditable(editable);
    txtAddress.setEditable(editable);
    txtPhone.setEditable(editable);
    txtSSS.setEditable(editable);
    txtTin.setEditable(editable);
    txtPhil.setEditable(editable);
    txtPIbig.setEditable(editable);
    txtSupervisor.setEditable(editable);
}
    //para kusang mag load yung table
    private void loadTableData(java.util.List<Employee> employees) {
    DefaultTableModel model = (DefaultTableModel) tblEmployees.getModel();
    model.setRowCount(0);

// kapag nag add ng new employee mag a-add ng new row para sa emp
    for (Employee emp : employees) {
        model.addRow(new Object[]{
            emp.getEmployeeByID(), emp.getName(),emp.getStatus()
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        tabEmployee = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtBirthday = new javax.swing.JTextField();
        txtPosition = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtTin = new javax.swing.JTextField();
        txtSSS = new javax.swing.JTextField();
        txtPhil = new javax.swing.JTextField();
        txtPIbig = new javax.swing.JTextField();
        txtSupervisor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnEditSave = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        comboMonth = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAttendance = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblDaysPresent = new javax.swing.JLabel();
        lblDaysAbsent = new javax.swing.JLabel();
        lblLate = new javax.swing.JLabel();
        lblOT = new javax.swing.JLabel();
        lblTotalWorked = new javax.swing.JLabel();
        comboYear = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        comboPayMonth = new javax.swing.JComboBox<>();
        comboPayYear = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        btnCompute = new javax.swing.JButton();
        btnExPaySlip = new javax.swing.JButton();
        lblBasicSalary = new javax.swing.JLabel();
        lblHourly = new javax.swing.JLabel();
        lblPayTotalHours = new javax.swing.JLabel();
        lblGrossPay = new javax.swing.JLabel();
        lblDeducSSS = new javax.swing.JLabel();
        lblDeducPhilHealth = new javax.swing.JLabel();
        lblDeducPIbig = new javax.swing.JLabel();
        lblNetPay = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lblDeducOthers = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblPayOT = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployees = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();

        btnAdd.setText("Add Employee");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tabEmployee.setInheritsPopupMenu(true);

        jLabel1.setText("Name:");

        jLabel2.setText("Employee #:");

        jLabel3.setText("Status:");

        jLabel4.setText("Position:");

        jLabel5.setText("Birthday:");

        jLabel6.setText("Address:");

        jLabel7.setText("Phone #:");

        jLabel8.setText("SSS #:");

        jLabel9.setText("Tin #:");

        jLabel10.setText("PhilHealth #:");

        jLabel11.setText("Pag-Ibig #:");

        txtName.setEditable(false);
        txtName.setBorder(null);
        txtName.setOpaque(true);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtStatus.setEditable(false);
        txtStatus.setBorder(null);
        txtStatus.setOpaque(true);

        txtID.setEditable(false);
        txtID.setBorder(null);
        txtID.setOpaque(true);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDKeyTyped(evt);
            }
        });

        txtBirthday.setEditable(false);
        txtBirthday.setBorder(null);
        txtBirthday.setOpaque(true);

        txtPosition.setEditable(false);
        txtPosition.setBorder(null);
        txtPosition.setOpaque(true);

        txtAddress.setEditable(false);
        txtAddress.setBorder(null);
        txtAddress.setOpaque(true);

        txtPhone.setEditable(false);
        txtPhone.setBorder(null);
        txtPhone.setOpaque(true);

        txtTin.setEditable(false);
        txtTin.setBorder(null);
        txtTin.setOpaque(true);
        txtTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTinActionPerformed(evt);
            }
        });

        txtSSS.setEditable(false);
        txtSSS.setBorder(null);
        txtSSS.setOpaque(true);
        txtSSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSSActionPerformed(evt);
            }
        });

        txtPhil.setEditable(false);
        txtPhil.setBorder(null);
        txtPhil.setOpaque(true);
        txtPhil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhilActionPerformed(evt);
            }
        });

        txtPIbig.setEditable(false);
        txtPIbig.setBorder(null);
        txtPIbig.setOpaque(true);

        txtSupervisor.setEditable(false);
        txtSupervisor.setBorder(null);
        txtSupervisor.setOpaque(true);

        jLabel12.setText("Immediate Supervisor:");

        btnEditSave.setText("Edit ");
        btnEditSave.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditSave)
                .addGap(27, 27, 27))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTin, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSSS, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPIbig, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhil, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPhil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtPIbig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(txtSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditSave)
                .addGap(17, 17, 17))
        );

        tabEmployee.addTab("Profile", jPanel2);

        comboMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        comboMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMonthActionPerformed(evt);
            }
        });

        tblAttendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Status", "Log-In", "Log-Out", "Overtime", "Total Hours"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAttendance.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(tblAttendance);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel14.setText("Monthly Summary");

        jLabel16.setText("Days Present: ");

        jLabel17.setText("Days Absent:");

        jLabel18.setText("Late Count:");

        jLabel19.setText("Total Overtime:");

        jLabel20.setText("Total Hours Worked:");

        lblDaysPresent.setText("...");

        lblDaysAbsent.setText("...");

        lblLate.setText("...");

        lblOT.setText("...");

        lblTotalWorked.setText("...");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDaysPresent)
                            .addComponent(jLabel14)
                            .addComponent(lblDaysAbsent)
                            .addComponent(lblLate)
                            .addComponent(lblOT)
                            .addComponent(lblTotalWorked))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblDaysPresent))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lblDaysAbsent))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lblLate))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(lblOT))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(lblTotalWorked))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        comboYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024", "2025" }));
        comboYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboYearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(comboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        comboMonth.getAccessibleContext().setAccessibleName("");
        comboMonth.getAccessibleContext().setAccessibleDescription("");

        tabEmployee.addTab("Performance", jPanel3);

        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setText("Monthly Pay");

        comboPayMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        comboPayMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPayMonthActionPerformed(evt);
            }
        });

        comboPayYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024", "2025" }));

        jLabel15.setText("Basic Salary :");

        jLabel21.setText("Hourly Rate :");

        jLabel22.setText("Hours Worked :");

        jLabel24.setText("Gross Pay :");

        jLabel25.setText("Deductions");

        jLabel26.setText("SSS :");

        jLabel28.setText("PhilHealth :");

        jLabel29.setText("Pag-Ibig :");

        jLabel30.setText("Net Pay :");

        btnCompute.setText("Compute");
        btnCompute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputeActionPerformed(evt);
            }
        });

        btnExPaySlip.setText("Export");
        btnExPaySlip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExPaySlipActionPerformed(evt);
            }
        });

        lblBasicSalary.setText("₱ ");

        lblHourly.setText("₱");

        lblPayTotalHours.setText("00:00");

        lblGrossPay.setText("₱");

        lblDeducSSS.setText("₱");

        lblDeducPhilHealth.setText("₱");

        lblDeducPIbig.setText("₱");

        lblNetPay.setText("₱");

        jLabel31.setText("Others :");

        lblDeducOthers.setText("₱");

        jLabel23.setText("Overtime :");

        lblPayOT.setText("00:00");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel13))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblBasicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHourly, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPayTotalHours, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel25))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnCompute, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnExPaySlip))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDeducPhilHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDeducPIbig, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDeducOthers, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNetPay, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDeducSSS, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGrossPay, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPayOT, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(comboPayMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(comboPayYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel13)
                .addGap(6, 6, 6)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPayMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboPayYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(lblBasicSalary))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(lblHourly))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(lblPayTotalHours))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(lblPayOT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(lblGrossPay))
                .addGap(22, 22, 22)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(lblDeducSSS, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(lblDeducPhilHealth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(lblDeducPIbig))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(lblDeducOthers))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(lblNetPay))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCompute)
                    .addComponent(btnExPaySlip))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(288, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        tabEmployee.addTab("Payroll ", jPanel4);

        txtSearch.setText("Search");
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        tblEmployees.setAutoCreateRowSorter(true);
        tblEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Employee #", "Name", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmployees.setToolTipText("");
        tblEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmployees);

        btnDelete.setText("Delete Employee");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSearch.setText("jButton1");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(btnAdd)
                                .addGap(45, 45, 45)
                                .addComponent(btnDelete)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(tabEmployee))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnDelete))
                .addGap(25, 25, 25))
        );

        jTabbedPane1.addTab("Employee Panel", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents
        
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
     //pupunta ka niya sa JDialog para mag add ng employees
        AddEmployee addDialog = new AddEmployee((JFrame) SwingUtilities.getWindowAncestor(this), true, employeeManager);
        addDialog.setVisible(true);
    
    loadTableData(employeeManager.getAllEmployees());

    
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtSSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSSActionPerformed

    private void txtTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTinActionPerformed

    private void tblEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeesMouseClicked
        
        // pag clinick mo yung employee sa employee lists lalabas yung multo ko jk
        //lalabas yung info sa right side
        int selectedRow = tblEmployees.getSelectedRow();
if (selectedRow >= 0) {
    String employeeID = tblEmployees.getValueAt(selectedRow, 0).toString();
    selectedEmployee = employeeManager.getEmployeeByID(employeeID);
    selectedEmployeeId = employeeID; 
    updateEmployeeTable();
    updateAttendanceTable();
   

    if (selectedEmployee != null) {
        txtID.setText(selectedEmployee.getEmployeeByID());
        txtName.setText(selectedEmployee.getName());        
        txtPosition.setText(selectedEmployee.getPosition());
        txtStatus.setText(selectedEmployee.getStatus());
        txtBirthday.setText(selectedEmployee.getBirthday());
        txtAddress.setText(selectedEmployee.getAddress());
        txtPhone.setText(selectedEmployee.getPhone());
        txtSSS.setText(selectedEmployee.getSssNumber());
        txtTin.setText(selectedEmployee.getTinNumber());
        txtPhil.setText(selectedEmployee.getPhilHealthNumber());
        txtPIbig.setText(selectedEmployee.getPagIbigNumber());
        txtSupervisor.setText(selectedEmployee.getSupervisor());
        

    }
 
    }//GEN-LAST:event_tblEmployeesMouseClicked
    }

    private void btnEditSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSaveActionPerformed
         if (!isEditing) {
        if (selectedEmployee == null) {
            JOptionPane.showMessageDialog(this, "Please select an employee.");
            return;
        }
 
        setFieldsEditable(true);
        isEditing = true;
        return;
}
                 
        int option = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to edit?",
                "Confirm Edit",
                JOptionPane.YES_NO_OPTION);
        
        if (option == JOptionPane.YES_OPTION) {
           
             String employeeID = txtID.getText();
             String name = txtName.getText();
             String position = txtPosition.getText();
             String status = txtStatus.getText();
             String birthday = txtBirthday.getText();
             String address = txtAddress.getText();
             String phone = txtPhone.getText();
             String supervisor = txtSupervisor.getText();
             String sssNumber = txtSSS.getText ();
             String tinNumber = txtTin.getText();
             String philHealthNumber = txtPhil.getText();
             String pagIbigNumber = txtPIbig.getText();
             
        Employee editEmp = new Employee(employeeID, name, position, birthday, address, phone, status, supervisor,
             sssNumber, tinNumber, pagIbigNumber, philHealthNumber);
        
         employeeManager.editEmployee(editEmp);
        selectedEmployee = editEmp;
        
       
  
         setFieldsEditable(false);
         isEditing = false;  
         loadTableData(employeeManager.getAllEmployees());


        }
    }//GEN-LAST:event_btnEditSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // Alam niyo na
        if (selectedEmployee == null) {
        JOptionPane.showMessageDialog(this, "Please select an employee.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, 
        "Are you sure you want to delete this employee?", 
        "Confirm Delete", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        employeeManager.deleteEmployee(selectedEmployee.getEmployeeByID());
        JOptionPane.showMessageDialog(this, "Employee deleted successfully.");
        selectedEmployee = null;
        
        loadTableData(employeeManager.getAllEmployees());
        
    }//GEN-LAST:event_btnDeleteActionPerformed
}
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
      //lam niyo na rin
        String keyword = txtSearch.getText().trim();
      if (!keyword.isEmpty()){
          List<Employee> results = employeeManager.searchEmployees(keyword);
        if (results.isEmpty()){
            JOptionPane.showMessageDialog(this, "No Matching Employees Found.");
            }
        loadTableData(results);
}else{ 
          loadTableData(employeeManager.getAllEmployees());
          //That's all thank yow
      }
              
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        btnSearchActionPerformed(evt);
        
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtPhilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhilActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void comboMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMonthActionPerformed
        
       updateAttendanceTable();
    }//GEN-LAST:event_comboMonthActionPerformed

    private void comboYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboYearActionPerformed
        updateAttendanceTable();
    }//GEN-LAST:event_comboYearActionPerformed

    private void txtIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume(); // Prevent non-digit characters from being entered
        }
    
    }//GEN-LAST:event_txtIDKeyTyped

    private void btnComputeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputeActionPerformed
      if (selectedEmployeeId == null || selectedEmployeeId.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No employee selected.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    Employee selectedEmp = employeeManager.getEmployeeByID(selectedEmployeeId);
    if (selectedEmp == null) {
        JOptionPane.showMessageDialog(this, "Employee not found.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String selectedMonth = (String) comboPayMonth.getSelectedItem();
    String selectedYear = (String) comboPayYear.getSelectedItem();

    
    DateTimeFormatter inputFormat = DateTimeFormatter.ofPattern("MMMM", Locale.ENGLISH);
    DateTimeFormatter outputFormat = DateTimeFormatter.ofPattern("MM");
    String monthNumber = outputFormat.format(inputFormat.parse(selectedMonth));

    // Get attendance for that employee and month
    List<Attendance> attendanceList = employeeManager.getAttendanceForEmployee(selectedEmployeeId, monthNumber, selectedYear);
    
    System.out.println("Selected Emp ID: " + selectedEmployeeId);
    System.out.println("Selected Month: " + selectedMonth);
    System.out.println("Selected Year: " + selectedYear);


    //Calculate hours worked
    int totalMinutesWorked = 0;
    int totalOvertimeMinutes = 0;

    for (Attendance record : attendanceList) {
        String[] analysis = AttendanceTracker.analyze(record);

        if (!analysis[4].equals("-")) {
            String[] total = analysis[4].split(":");
            int hours = Integer.parseInt(total[0].trim());
            int minutes = Integer.parseInt(total[1].trim());
            totalMinutesWorked += (hours * 60) + minutes;
        }

        if (!analysis[3].equals("00:00") && !analysis[3].equals("-")) {
            String[] OT = analysis[3].split(":");
           int otHours = Integer.parseInt(OT[0]);
           int otMinutes = Integer.parseInt(OT[1]);
           totalOvertimeMinutes += (otHours * 60) + otMinutes;
        }    
    }
    // salary info
    double basicSalary = selectedEmp.getBasicSalary(); 
    double hourlyRate = selectedEmp.getHourlyRate();    
    double totalHours = totalMinutesWorked / 60.0;
    double totalOT = totalOvertimeMinutes / 60.0;
    double grossPay = totalHours * hourlyRate;
    
     double others = 0.0;
    try {
        String otherText = lblDeducOthers.getText().trim().replace("₱", "").replace(",", "");
        if (!otherText.isEmpty()) {
            others = Double.parseDouble(otherText);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter a valid amount for Other Deductions.");
        return;
    }

    //Deductions
    double sss = grossPay * 0.15;
    double philHealth = grossPay * 0.05;
    double pagibig = grossPay * 0.02;
    double totalDeductions = others + sss + philHealth + pagibig;

    // Net Pay
    double netPay = grossPay - totalDeductions;
    
    // Changes ...
    lblBasicSalary.setText("₱" + String.format("%,.2f", basicSalary));
    lblHourly.setText("₱" + String.format("%,.2f", hourlyRate));
    lblPayTotalHours.setText(String.format("%.2f", totalHours)+ " hours");
    lblPayOT.setText(String.format("%.2f", totalOT)+ " hours");
    lblGrossPay.setText("₱" + String.format("%,.2f", grossPay));
    lblDeducSSS.setText("₱" + String.format("%,.2f", sss));
    lblDeducPhilHealth.setText("₱" + String.format("%,.2f", philHealth));
    lblDeducPIbig.setText("₱" + String.format("%,.2f", pagibig));
    lblDeducOthers.setText("₱" + String.format("%,.2f", pagibig));
    lblNetPay.setText("₱" + String.format("%,.2f", netPay));
    }//GEN-LAST:event_btnComputeActionPerformed

    private void btnExPaySlipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExPaySlipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExPaySlipActionPerformed

    private void comboPayMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPayMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPayMonthActionPerformed
    //EMPLOYEE CSV
   private void loadEmployeeDataFromCSV() {
    try (CSVReader csvReader = new CSVReader(new FileReader("CSV/employees.csv"))) {
        List<String[]> records = csvReader.readAll();
        for (String[] line : records) {
            if (line.length >= 12) {
                Employee emp = new Employee(
                    line[0], line[1], line[2], line[3], line[4], line[5],
                    line[6], line[7], line[8], line[9], line[10], line[11]
                );
                employeeManager.addEmployee(emp);
            }
        }
         employeeManager.loadPayrollDataFromCSV();
    } catch (IOException e) {
    }
}

//EMPLOYEE TABLE REFRESHER
private void updateEmployeeTable() {
    DefaultTableModel model = (DefaultTableModel) tblEmployees.getModel();
    model.setRowCount(0);

    for (Employee emp : employeeManager.getAllEmployees()) {
        Object[] row = {
            emp.getEmployeeByID(), emp.getName(),emp.getStatus()
         
        };
        model.addRow(row);
    }
}
//ATTENDANCE TABLE REFRESHER
    private void updateAttendanceTable() {
    if (selectedEmployeeId == null || selectedEmployeeId.isEmpty()) {
        return; 
    }

    String selectedMonth = (String) comboMonth.getSelectedItem();
    String selectedYear = (String) comboYear.getSelectedItem();

    
    DateTimeFormatter inputFormat = DateTimeFormatter.ofPattern("MMMM", Locale.ENGLISH);
    DateTimeFormatter outputFormat = DateTimeFormatter.ofPattern("MM");
    String monthNumber = outputFormat.format(inputFormat.parse(selectedMonth));

    List<Attendance> records = employeeManager.getAttendanceForEmployee(selectedEmployeeId, monthNumber, selectedYear);

    DefaultTableModel model = (DefaultTableModel) tblAttendance.getModel();
    model.setRowCount(0); 

    int totalDays = records.size();
    int presentCount = 0;
    int absentCount = 0;
    int lateCount = 0;
    int totalOvertimeMinutes = 0;
    int totalWorkedMinutes = 0;

    for (Attendance record : records) {
        String[] analysis = AttendanceTracker.analyze(record);
        String status = analysis[0].toLowerCase();
        
        model.addRow(new Object[]{
            record.getDate().toString(),
            analysis[0],  // Status: Present / Late / Absent
            analysis[1],  // Time In
            analysis[2],  // Time Out
            analysis[3],  // Overtime
            analysis[4]   // Total Hours
        });

        
    if (!status.contains("absent") && !status.contains("missed log")) {
        presentCount++;
}

    // Count as late if "late" is mentioned in status <3
    if (status.contains("late")) {
        lateCount++;
}
    if (record.getTimeIn() != null && record.getTimeOut() != null) {
    Duration worked = Duration.between(record.getTimeIn(), record.getTimeOut());
    totalWorkedMinutes += worked.toMinutes();
}



        if (!analysis[3].equals("00:00")) {
                String[] parts = analysis[3].split(":");
                int hours = Integer.parseInt(parts[0]);
                int minutes = Integer.parseInt(parts[1]);
                totalOvertimeMinutes += (hours * 60 + minutes);
                
                
}
}
        int otHours = totalOvertimeMinutes / 60;
        int otMinutes = totalOvertimeMinutes % 60;
        String totalOvertimeFormatted = String.format("%02d:%02d", otHours, otMinutes);
        int workedHours = totalWorkedMinutes / 60;
        int workedMinutes = totalWorkedMinutes % 60;
        String totalWorkedFormatted = String.format("%02d:%02d", workedHours, workedMinutes);


        
// changes ... 
    lblDaysPresent.setText( presentCount + " / " + totalDays);
    lblDaysAbsent.setText( absentCount + " / " + totalDays);
    lblLate.setText("" + lateCount);
    lblOT.setText( totalOvertimeFormatted);
    lblTotalWorked.setText(totalWorkedFormatted);
}

  



    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCompute;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEditSave;
    private javax.swing.JButton btnExPaySlip;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> comboMonth;
    private javax.swing.JComboBox<String> comboPayMonth;
    private javax.swing.JComboBox<String> comboPayYear;
    private javax.swing.JComboBox<String> comboYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblBasicSalary;
    private javax.swing.JLabel lblDaysAbsent;
    private javax.swing.JLabel lblDaysPresent;
    private javax.swing.JLabel lblDeducOthers;
    private javax.swing.JLabel lblDeducPIbig;
    private javax.swing.JLabel lblDeducPhilHealth;
    private javax.swing.JLabel lblDeducSSS;
    private javax.swing.JLabel lblGrossPay;
    private javax.swing.JLabel lblHourly;
    private javax.swing.JLabel lblLate;
    private javax.swing.JLabel lblNetPay;
    private javax.swing.JLabel lblOT;
    private javax.swing.JLabel lblPayOT;
    private javax.swing.JLabel lblPayTotalHours;
    private javax.swing.JLabel lblTotalWorked;
    private javax.swing.JTabbedPane tabEmployee;
    private javax.swing.JTable tblAttendance;
    private javax.swing.JTable tblEmployees;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBirthday;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPIbig;
    private javax.swing.JTextField txtPhil;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtSSS;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtSupervisor;
    private javax.swing.JTextField txtTin;
    // End of variables declaration//GEN-END:variables

    
}

